### ISSUE TITLE
Header is transparent

### ISSUE THREAD

**Issue by capital-G** [Gencaster/gencaster.github.io#13]
<img width="1752" alt="image" src="https://user-images.githubusercontent.com/8267062/236570815-e3380a3b-00d7-4a49-bf13-ec16f6ce2bb8.png">

which can be fixed here https://github.com/Gencaster/gencaster.github.io/blob/main/components/Header.vue

2 propositions

## White background

<img width="978" alt="image" src="https://user-images.githubusercontent.com/8267062/236571462-cc0f1bfd-a124-4fdb-81e5-6ea925b8dc1a.png">

```css
.header-container {
  background-color: white
}
```

## Blurry background

<img width="975" alt="image" src="https://user-images.githubusercontent.com/8267062/236571412-329e029f-2a60-4852-99ed-4e7e5b0645b5.png">

```css
.header-container {
  background-color: rgba(255, 255, 255, .15);
  backdrop-filter: blur(5px);
}
```
